### ISSUE TITLE
Problem with JSON.stringify on binary BLOB fields

### ISSUE THREAD

**Issue by erf** [WebReflection/dblite#19]
When dblite uses JSON.stringify on binary BLOB fields, there is a problem when i want to use  sqlite3 dbs created by others with binary data (not stringified). I now need to have two different ways of parsing them. I wish BLOB fields where not stringified, or one could make it optional.

**Comment by NanduriSaiJyothiMalathi** [comment]
Hi ,
I have huge number of json data to stringfy and send to server . As my UI not responding while executing that line  so i decided to send the data as file to server instead of stringfying it . 

Is blob in javascript can be useful?

Please let me know how can i do this . Thanks in advance.
