### ISSUE TITLE
Database is locked

### ISSUE THREAD

**Issue by nkint** [WebReflection/dblite#30]
Sorry, here again.
I am testing the system done with dblite and after a two days of testing I got this error:

````Error: Error: near line 44372: database is locked```

It caused the next query to fail.
Is there any workaround? Or maybe I'm handling the errors in the wrong way?

**Comment by WebReflection** [comment]
had no answer in ages, will close this

**Comment by nkint** [comment]
yes, sorry, it is resolved. thanks!
