### ISSUE TITLE
db.plain returns parsed value anyway

### ISSUE THREAD

**Issue by rumkin** [WebReflection/dblite#37]
Accordingly with this [line 275](https://github.com/WebReflection/dblite/blob/master/src/dblite.js#L275) variable `dontParseCSV` will be equal `false` always on the check at [the line 285](https://github.com/WebReflection/dblite/blob/master/src/dblite.js#L285).

**Comment by WebReflection** [comment]
cn you please provide a failing example?

**Comment by rumkin** [comment]
Sure.
```javascript
var db = dblite('store.db');
db.plain('SELECT * FROM some_table;', function(err, unparsed) {
    console.log(typeof unparsed); // -> object (should be a string)
});
```

**Comment by WebReflection** [comment]
that is doing what it's expect to do ... can you please provide me an example that shows any real problem?

**Comment by rumkin** [comment]
Isn't `plain` method should return unparsed CSV instead of Object?

**Comment by WebReflection** [comment]
you are right, I'm blind. I've read that as `db.query` ..... and `0.7.6` should work as expected. Thanks

**Comment by rumkin** [comment]
You are welcome
