### ISSUE TITLE
error detection

### ISSUE THREAD

**Issue by strogof** [WebReflection/dblite#38]
hi,

what is wrong on this? (apologies for my english...)

win server 2012

PS C:\consip> node -v
v0.12.1

PS C:\consip> npm list dblite
C:\consip
└── dblite@0.7.6

PS C:\consip> sqlite3
SQLite version 3.8.8.3 2015-02-25 13:29:11
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> .ex

PS C:\consip> type .\testErr.js
var dblite = require('dblite'),
    consipDB = dblite('consip.db');
consipDB.query(
        "select * ffrom utenti where nome=?",["pp"],
        function(err1, rows) {
                console.log(err1,rows)
        }
);

PS C:\consip> node .\testErr.js
null []

**Comment by WebReflection** [comment]
`ffrom` instead of `from`, that's why it's a good practice to write SQL commands CAPITALIZED, it helps finding errors

`SELECT * FROM utenti WHERE nome=?`

Please note on windows there's some asynchronous error notification. In your case it looks actually that errors are not triggered at all.

**Comment by strogof** [comment]
thanks for the quick response..
the problem is that the error is not detected (err1=null)

**Comment by WebReflection** [comment]
like I've said, there are problems in Windows with the error handling. There is already a bug report regarding this, please be sure your SQL strings are valid for the time being. these are all errors that should never land in productions anyway.

This is [a known issue](https://github.com/WebReflection/dblite/issues/36), I'll close this as duplicated. Apologies for any inconvenient.

**Comment by strogof** [comment]
ok, sorry and thanks again..
