### ISSUE TITLE
Error: spawn sqlite3 ENOENT when creating db 

### ISSUE THREAD

**Issue by mrigo** [WebReflection/dblite#44]
Hi,
I've installed dblite on my raspberry pi and when I'm trying to instantiate a db

```
var dblite = require('dblite');
var db_path = __dirname+'/db/db.sqlite';
db = dblite(db_path, '-header');
```

and run node app.js, I'm having this error

`Error: spawn sqlite3 ENOENT`

The db exists and is readable and the path is correct.

On OSX the error doesn't appear.

Thanks!
\m

**Comment by WebReflection** [comment]
do you have sqlite3 installed ?

```sh
$ which sqlite3
/usr/bin/sqlite3
```

if your output is different, please specify the right path for the executable as explained in the Readme.

example
```js
var dblite = require('dblite');
dblite.bin = "/usr/local/bin/sqlite3";

var db_path = __dirname+'/db/db.sqlite';
var db = dblite(db_path, '-header');
```

**Comment by WebReflection** [comment]
no reply over almost a year.
