### ISSUE TITLE
Error: Error: near line 1: near "2": syntax error

### ISSUE THREAD

**Issue by agdolla** [WebReflection/dblite#46]
When I try to do an update and the property name ends with 2 it fails with
Error: Error: near line 1: near "2": syntax error

```sql
update mytable set email2=@email2 where id=@id
```

**Comment by WebReflection** [comment]
it should be fixed with `0.7.8`

if that's the case, please close this issue. Thanks

**Comment by agdolla** [comment]
thanks!
