### ISSUE TITLE
sqlite json functions don't work

### ISSUE THREAD

**Issue by agdolla** [WebReflection/dblite#48]
from command line this works:

```
sqlite> select * from json_each(json_array(20170318,20170319,20170329));
0|20170318|integer|20170318|1||$[0]|$
1|20170319|integer|20170319|2||$[1]|$
2|20170329|integer|20170329|3||$[2]|$
```

from dblite it results:
```
[ {}, {}, {} ]
```

**Comment by WebReflection** [comment]
Quickly checked, I actually have a syntax error.

Which version of sqlite are you using and for which platform?

**Comment by WebReflection** [comment]
![screenshot from 2017-03-27 18-57-11](https://cloud.githubusercontent.com/assets/85749/24370422/3f6b78b2-131f-11e7-9dcc-5e6bb201fa72.png)

it works like a charm where supported
