### ISSUE TITLE
how make it run on Windows

### ISSUE THREAD

**Issue by antanse** [WebReflection/dblite#50]
I work on windows 7, and install the sqlite3 in the folder C:\albert\sqlite, both sqlite3.dll and sqlite3.exe exist in this folder. and I installed dblite ( npm install dblite ) in my Visual Studio Code.
and create a database file named 'abc.db' and a source code file app.js, it contains the following source codes.
var dblite = require('dblite');
db = dblite('./abc.db');

however it throw the following error:
Exception has occurred: Error
Error: kill EINVAL
    at exports._errnoException (util.js:1018:11)
    at ChildProcess.kill (internal/child_process.js:397:13)
    at setUpAndGo (c:\albert\NetCode\NodejsWorkspace\dblitetest\node_modules\dblite\build\dblite.node.js:162:19)
    at Socket.onerror (c:\albert\NetCode\NodejsWorkspace\dblitetest\node_modules\dblite\build\dblite.node.js:135:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at onwriteError (_stream_writable.js:343:10)
    at onwrite (_stream_writable.js:361:5)
    at __dirname.WritableState.stream.onwrite (_stream_writable.js:90:5)
    at fireErrorCallbacks (net.js:467:13)

would you please take a look at this issue or give me some ideas to make it run on Windows

**Comment by WebReflection** [comment]
try both this
`var dblite = require('dblite').withSQLite('3.8.6+');`
and the following too
`dblite.bin = 'absolute-path-to-your-sqlite3-file';`

not necessarily together

**Comment by antanse** [comment]
many thanks, the followings works
```javascript
var dblite = require('dblite').withSQLite('3.8.6+');
```
what is the reason?

**Comment by WebReflection** [comment]
> It seems that sqlite3 version 3.8.8+ introduced a new line \n on Windows machines too so the whole initialization is now performed asynchronously and through features detection.

https://github.com/WebReflection/dblite#updates

**Comment by barbalex** [comment]
Same problem here. But now I am utterly confused: is `'/folder/to/file.sqlite'` the path to the sqlite .db file or is it the path to a sqlite exe file?

**Comment by WebReflection** [comment]
files with `.sqlite` extensions are usually sqlite databases 

the file set as `prog.bin = '...'` is the binary file / executable file

this project works on windows too

**Comment by barbalex** [comment]
Thanks for helping, I _may_ have gotten it right. Can't test it yet though because of problems with my create-react-app using electron setup :-(
