### ISSUE TITLE
Does not handle CTEs (WITH keyword)

### ISSUE THREAD

**Issue by dataspoon** [WebReflection/dblite#51]
dblite does not handle CTEs
https://www.sqlite.org/lang_with.html

The verify select method needs to be modified to include WITH|with.

An example of a CTE:
WITH test(name) AS (
SELECT "JOHN"
)
SELECT name
FROM test;

**Comment by WebReflection** [comment]
you mean here ? https://github.com/WebReflection/dblite/blob/master/src/dblite.js#L45
