### ISSUE TITLE
How to run queries synchronously?

### ISSUE THREAD

**Issue by bradparks** [WebReflection/dblite#6]
Hey there;

I'd like to be able to run some queries synchronously. Is there a way to do so?

In it's simplest form, I'd like to call db.query and get an array of records back in a blocking manner.

e.g

``` javascript
// the following is not how db.query works. It's how I'd *like* it to work sometimes
var rows = db.query('SELECT * FROM test');
console.log(rows)
// this would print an array of records to the console.
```

Is this possible?  I'd like to do it for inserts, and deletes as well. Thanks!

**Comment by RaedsLab** [comment]
Why not just offer the developers a synchronous option?

**Comment by WebReflection** [comment]
> But I'm not sure it's even possible to implement a querySync method since dblite reads from stdin, and doing blocking reads from stdin is AFAIK not possible in node.

**Comment by jhoughjr** [comment]
sure could use a synchronous option, kinda hard to build html in nested callbacks a mile deep!

**Comment by WebReflection** [comment]
actually a piece of cake with [viperHTML](https://github.com/WebReflection/viperHTML), just make those callbacks a Promise and pass it along
